# =========================
# Name
# =========================
spring.application.name=Night-Cinema

# =========================
# Supabase : Database Config(PostgresSQL)
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================
# Hibernate Config
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# Secret Key (JWT)
# =========================
secret_key=${SECRET_KEY}
access_token_expiration=60000
refresh_token_expiration=604800000

# =========================
# Cloudinary Config
# =========================
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}