package az.duo.Night.Cinema.entity;

public enum Permission {
    ADD_USER, DELETE_USER, UPDATE_USER,
    ADD_ADMIN, DELETE_ADMIN, UPDATE_ADMIN,
    ADD_MOVIE, DELETE_MOVIE, UPDATE_MOVIE,
    ADD_MOVIE_SESSION, DELETE_MOVIE_SESSION, UPDATE_MOVIE_SESSION,
    ADD_ROOM, DELETE_ROOM,
    ADD_LANGUAGE, REMOVE_LANGUAGE,
    ADD_PROFILE_PHOTO_URL, REMOVE_PROFILE_PHOTO_URL
}
